### ISSUE TITLE
Will a generic RGB webcam work?

### ISSUE THREAD

**Issue by se1exin** [ycheng517/tabletop-handybot#1]
Hi there, this is awesome and I'm keen to try it out with my AR4. Just wondering, is a depth camera required or will a simple RBG work (obviously will need switching the camera driver in the launch file)?

I ask because I noticed in the code it appears to be using depth data in the pick and place function: https://github.com/ycheng517/tabletop-handybot/blob/27e23a0b66b3ea5068662948b96b0977adf41bf0/tabletop_handybot/tabletop_handybot/tabletop_handybot_node.py#L339

Obviously a generic RGB camera would not have this depth info. Unless I am missing something? (I've only briefly read the code to get an idea of how you put this together).

This might give me a good excuse to buy a realsense depth camera though 😁

**Comment by ycheng517** [comment]
RGBD camera is required, otherwise you'll need to add another ML model to get depth from RGB, There's a bunch of models available here: https://paperswithcode.com/task/monocular-depth-estimation. I'd rather not worry about this complexity (as these models aren't perfect) and just get the Realsense.

**Comment by se1exin** [comment]
Thanks for clarifying and confirming that. I agree with you that just getting a Realsense will be the path of least resistance for depth data - time to go shopping!
